services:
  # Backend API Service
  - type: web
    name: deo-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://deo-frontend.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: SCRAPEOWL_API_KEY
        sync: false
      - key: APOLLO_API_KEY
        sync: false
      - key: HUNTER_API_KEY
        sync: false
      - key: PEOPLEDATALABS_API_KEY
        sync: false
      - key: PROSPEO_API_KEY
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
    healthCheckPath: /health

  # Frontend Service
  - type: web
    name: deo-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://deo-backend.onrender.com
      - key: VITE_OPENAI_API_KEY
        sync: false
      - key: VITE_SERPAPI_KEY
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 